### ISSUE TITLE
What will be new?

### ISSUE THREAD

**Issue by LiuG-lynx** [laiyongtao/aio_nameko_proxy#2]
I would love to contribute to this Repo, but I don't know where to start. Can you give me some help?thank you

**Comment by laiyongtao** [comment]
I have no plan yet~ !^_^

**Comment by LiuG-lynx** [comment]
Can you package and upgrade the version @laiyongtao   1.2.0 does not have FastAPI Proxy

**Comment by laiyongtao** [comment]
ok, done. and you can use "pip install aio-nameko-proxy" to install it from pypi
